* Introduction
Along these lines, I ran across this great summary of TDD recently in
the book *AngularJS, Up and Running*.


Test-driven development, or TDD, is an AGILE methodology that flips
the development life cycle by ensuring that tests are written, before
the code is implemented, and that tests drive the development (and are
not just used as a validation tool).

The tenets of TDD are simple:

- Code is written only when there is a failing test that requires the
  code to pass.
- The bare minimum amount of code is written to ensure that the test
  passes.
- Duplication is removed at every step.
- When all tests pass, the next failing test is added for the next
  required functionality.

These simple rules ensure that:

- Code develops organically, and that every line of code is
  purposeful.
- Code remains highly modular, cohesive, and reusable (because we need
  to be able to test it).
- We provide a comprehensive array of tests to prevent future
  breakages and bugs.
- The tests also act as specification, and thus documentation, for
  future needs and changes.
